

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: PRODUCT-SERVICE

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    password: root
    baseline-version: 0
    baseline-description: "init"